/* Generated by scripts/generate_libclang_bindings.py - do not edit by hand. */
#include "libclang_mojo_shim.h"

typedef struct MojoCXCursorVisitorContext {
    enum CXChildVisitResult (*fn)(CXCursor *arg0, CXCursor *arg1, void * arg2);
    void *client_data;
} MojoCXCursorVisitorContext;

static enum CXChildVisitResult mojo_CXCursorVisitor_trampoline(CXCursor arg0, CXCursor arg1, void * arg2) {
    MojoCXCursorVisitorContext *ctx = (MojoCXCursorVisitorContext *)arg2;
    return ctx->fn(&arg0, &arg1, ctx->client_data);
}

typedef struct MojoCXFieldVisitorContext {
    enum CXVisitorResult (*fn)(CXCursor *arg0, void * arg1);
    void *client_data;
} MojoCXFieldVisitorContext;

static enum CXVisitorResult mojo_CXFieldVisitor_trampoline(CXCursor arg0, void * arg1) {
    MojoCXFieldVisitorContext *ctx = (MojoCXFieldVisitorContext *)arg1;
    return ctx->fn(&arg0, ctx->client_data);
}

typedef struct MojoCXCursorAndRangeVisitorContext {
    CXCursorAndRangeVisitor *visitor;
} MojoCXCursorAndRangeVisitorContext;

static enum CXVisitorResult mojo_CXCursorAndRangeVisitor_trampoline(
    void *context,
    CXCursor cursor,
    CXSourceRange range
) {
    MojoCXCursorAndRangeVisitorContext *ctx = (MojoCXCursorAndRangeVisitorContext *)context;
    return ((enum CXVisitorResult (*)(void *, CXCursor *, CXSourceRange *))ctx->visitor->visit)(
        ctx->visitor->context,
        &cursor,
        &range
    );
}

MOJO_SHIM_EXPORT const char * mojo_clang_getCString(const CXString * string) {
    return clang_getCString(*string);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeString(const CXString * string) {
    clang_disposeString(*string);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeStringSet(CXStringSet * set) {
    clang_disposeStringSet(set);
}

MOJO_SHIM_EXPORT unsigned long long mojo_clang_getBuildSessionTimestamp(void) {
    return clang_getBuildSessionTimestamp();
}

MOJO_SHIM_EXPORT CXVirtualFileOverlay mojo_clang_VirtualFileOverlay_create(unsigned int options) {
    return clang_VirtualFileOverlay_create(options);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_VirtualFileOverlay_addFileMapping(CXVirtualFileOverlay arg0, const char * virtualPath, const char * realPath) {
    return clang_VirtualFileOverlay_addFileMapping(arg0, virtualPath, realPath);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_VirtualFileOverlay_setCaseSensitivity(CXVirtualFileOverlay arg0, int caseSensitive) {
    return clang_VirtualFileOverlay_setCaseSensitivity(arg0, caseSensitive);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_VirtualFileOverlay_writeToBuffer(CXVirtualFileOverlay arg0, unsigned int options, char * * out_buffer_ptr, unsigned int * out_buffer_size) {
    return clang_VirtualFileOverlay_writeToBuffer(arg0, options, out_buffer_ptr, out_buffer_size);
}

MOJO_SHIM_EXPORT void mojo_clang_free(void * buffer) {
    clang_free(buffer);
}

MOJO_SHIM_EXPORT void mojo_clang_VirtualFileOverlay_dispose(CXVirtualFileOverlay arg0) {
    clang_VirtualFileOverlay_dispose(arg0);
}

MOJO_SHIM_EXPORT CXModuleMapDescriptor mojo_clang_ModuleMapDescriptor_create(unsigned int options) {
    return clang_ModuleMapDescriptor_create(options);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_ModuleMapDescriptor_setFrameworkModuleName(CXModuleMapDescriptor arg0, const char * name) {
    return clang_ModuleMapDescriptor_setFrameworkModuleName(arg0, name);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_ModuleMapDescriptor_setUmbrellaHeader(CXModuleMapDescriptor arg0, const char * name) {
    return clang_ModuleMapDescriptor_setUmbrellaHeader(arg0, name);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_ModuleMapDescriptor_writeToBuffer(CXModuleMapDescriptor arg0, unsigned int options, char * * out_buffer_ptr, unsigned int * out_buffer_size) {
    return clang_ModuleMapDescriptor_writeToBuffer(arg0, options, out_buffer_ptr, out_buffer_size);
}

MOJO_SHIM_EXPORT void mojo_clang_ModuleMapDescriptor_dispose(CXModuleMapDescriptor arg0) {
    clang_ModuleMapDescriptor_dispose(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getFileName(CXString * out, CXFile SFile) {
    *out = clang_getFileName(SFile);
}

MOJO_SHIM_EXPORT time_t mojo_clang_getFileTime(CXFile SFile) {
    return clang_getFileTime(SFile);
}

MOJO_SHIM_EXPORT int mojo_clang_getFileUniqueID(CXFile file, CXFileUniqueID * outID) {
    return clang_getFileUniqueID(file, outID);
}

MOJO_SHIM_EXPORT int mojo_clang_File_isEqual(CXFile file1, CXFile file2) {
    return clang_File_isEqual(file1, file2);
}

MOJO_SHIM_EXPORT void mojo_clang_File_tryGetRealPathName(CXString * out, CXFile file) {
    *out = clang_File_tryGetRealPathName(file);
}

MOJO_SHIM_EXPORT void mojo_clang_getNullLocation(CXSourceLocation * out) {
    *out = clang_getNullLocation();
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_equalLocations(const CXSourceLocation * loc1, const CXSourceLocation * loc2) {
    return clang_equalLocations(*loc1, *loc2);
}

MOJO_SHIM_EXPORT int mojo_clang_Location_isInSystemHeader(const CXSourceLocation * location) {
    return clang_Location_isInSystemHeader(*location);
}

MOJO_SHIM_EXPORT int mojo_clang_Location_isFromMainFile(const CXSourceLocation * location) {
    return clang_Location_isFromMainFile(*location);
}

MOJO_SHIM_EXPORT void mojo_clang_getNullRange(CXSourceRange * out) {
    *out = clang_getNullRange();
}

MOJO_SHIM_EXPORT void mojo_clang_getRange(CXSourceRange * out, const CXSourceLocation * begin, const CXSourceLocation * end) {
    *out = clang_getRange(*begin, *end);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_equalRanges(const CXSourceRange * range1, const CXSourceRange * range2) {
    return clang_equalRanges(*range1, *range2);
}

MOJO_SHIM_EXPORT int mojo_clang_Range_isNull(const CXSourceRange * range) {
    return clang_Range_isNull(*range);
}

MOJO_SHIM_EXPORT void mojo_clang_getExpansionLocation(const CXSourceLocation * location, CXFile * file, unsigned int * line, unsigned int * column, unsigned int * offset) {
    clang_getExpansionLocation(*location, file, line, column, offset);
}

MOJO_SHIM_EXPORT void mojo_clang_getPresumedLocation(const CXSourceLocation * location, CXString * filename, unsigned int * line, unsigned int * column) {
    clang_getPresumedLocation(*location, filename, line, column);
}

MOJO_SHIM_EXPORT void mojo_clang_getInstantiationLocation(const CXSourceLocation * location, CXFile * file, unsigned int * line, unsigned int * column, unsigned int * offset) {
    clang_getInstantiationLocation(*location, file, line, column, offset);
}

MOJO_SHIM_EXPORT void mojo_clang_getSpellingLocation(const CXSourceLocation * location, CXFile * file, unsigned int * line, unsigned int * column, unsigned int * offset) {
    clang_getSpellingLocation(*location, file, line, column, offset);
}

MOJO_SHIM_EXPORT void mojo_clang_getFileLocation(const CXSourceLocation * location, CXFile * file, unsigned int * line, unsigned int * column, unsigned int * offset) {
    clang_getFileLocation(*location, file, line, column, offset);
}

MOJO_SHIM_EXPORT void mojo_clang_getRangeStart(CXSourceLocation * out, const CXSourceRange * range) {
    *out = clang_getRangeStart(*range);
}

MOJO_SHIM_EXPORT void mojo_clang_getRangeEnd(CXSourceLocation * out, const CXSourceRange * range) {
    *out = clang_getRangeEnd(*range);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeSourceRangeList(CXSourceRangeList * ranges) {
    clang_disposeSourceRangeList(ranges);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getNumDiagnosticsInSet(CXDiagnosticSet Diags) {
    return clang_getNumDiagnosticsInSet(Diags);
}

MOJO_SHIM_EXPORT CXDiagnostic mojo_clang_getDiagnosticInSet(CXDiagnosticSet Diags, unsigned int Index) {
    return clang_getDiagnosticInSet(Diags, Index);
}

MOJO_SHIM_EXPORT CXDiagnosticSet mojo_clang_loadDiagnostics(const char * file, enum CXLoadDiag_Error * error, CXString * errorString) {
    return clang_loadDiagnostics(file, error, errorString);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeDiagnosticSet(CXDiagnosticSet Diags) {
    clang_disposeDiagnosticSet(Diags);
}

MOJO_SHIM_EXPORT CXDiagnosticSet mojo_clang_getChildDiagnostics(CXDiagnostic D) {
    return clang_getChildDiagnostics(D);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeDiagnostic(CXDiagnostic Diagnostic) {
    clang_disposeDiagnostic(Diagnostic);
}

MOJO_SHIM_EXPORT void mojo_clang_formatDiagnostic(CXString * out, CXDiagnostic Diagnostic, unsigned int Options) {
    *out = clang_formatDiagnostic(Diagnostic, Options);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_defaultDiagnosticDisplayOptions(void) {
    return clang_defaultDiagnosticDisplayOptions();
}

MOJO_SHIM_EXPORT enum CXDiagnosticSeverity mojo_clang_getDiagnosticSeverity(CXDiagnostic arg0) {
    return clang_getDiagnosticSeverity(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticLocation(CXSourceLocation * out, CXDiagnostic arg1) {
    *out = clang_getDiagnosticLocation(arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticSpelling(CXString * out, CXDiagnostic arg1) {
    *out = clang_getDiagnosticSpelling(arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticOption(CXString * out, CXDiagnostic Diag, CXString * Disable) {
    *out = clang_getDiagnosticOption(Diag, Disable);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getDiagnosticCategory(CXDiagnostic arg0) {
    return clang_getDiagnosticCategory(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticCategoryName(CXString * out, unsigned int Category) {
    *out = clang_getDiagnosticCategoryName(Category);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticCategoryText(CXString * out, CXDiagnostic arg1) {
    *out = clang_getDiagnosticCategoryText(arg1);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getDiagnosticNumRanges(CXDiagnostic arg0) {
    return clang_getDiagnosticNumRanges(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticRange(CXSourceRange * out, CXDiagnostic Diagnostic, unsigned int Range) {
    *out = clang_getDiagnosticRange(Diagnostic, Range);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getDiagnosticNumFixIts(CXDiagnostic Diagnostic) {
    return clang_getDiagnosticNumFixIts(Diagnostic);
}

MOJO_SHIM_EXPORT void mojo_clang_getDiagnosticFixIt(CXString * out, CXDiagnostic Diagnostic, unsigned int FixIt, CXSourceRange * ReplacementRange) {
    *out = clang_getDiagnosticFixIt(Diagnostic, FixIt, ReplacementRange);
}

MOJO_SHIM_EXPORT CXIndex mojo_clang_createIndex(int excludeDeclarationsFromPCH, int displayDiagnostics) {
    return clang_createIndex(excludeDeclarationsFromPCH, displayDiagnostics);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeIndex(CXIndex index) {
    clang_disposeIndex(index);
}

MOJO_SHIM_EXPORT CXIndex mojo_clang_createIndexWithOptions(const CXIndexOptions * options) {
    return clang_createIndexWithOptions(options);
}

MOJO_SHIM_EXPORT void mojo_clang_CXIndex_setGlobalOptions(CXIndex arg0, unsigned int options) {
    clang_CXIndex_setGlobalOptions(arg0, options);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXIndex_getGlobalOptions(CXIndex arg0) {
    return clang_CXIndex_getGlobalOptions(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_CXIndex_setInvocationEmissionPathOption(CXIndex arg0, const char * Path) {
    clang_CXIndex_setInvocationEmissionPathOption(arg0, Path);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isFileMultipleIncludeGuarded(CXTranslationUnit tu, CXFile file) {
    return clang_isFileMultipleIncludeGuarded(tu, file);
}

MOJO_SHIM_EXPORT CXFile mojo_clang_getFile(CXTranslationUnit tu, const char * file_name) {
    return clang_getFile(tu, file_name);
}

MOJO_SHIM_EXPORT const char * mojo_clang_getFileContents(CXTranslationUnit tu, CXFile file, size_t * size) {
    return clang_getFileContents(tu, file, size);
}

MOJO_SHIM_EXPORT void mojo_clang_getLocation(CXSourceLocation * out, CXTranslationUnit tu, CXFile file, unsigned int line, unsigned int column) {
    *out = clang_getLocation(tu, file, line, column);
}

MOJO_SHIM_EXPORT void mojo_clang_getLocationForOffset(CXSourceLocation * out, CXTranslationUnit tu, CXFile file, unsigned int offset) {
    *out = clang_getLocationForOffset(tu, file, offset);
}

MOJO_SHIM_EXPORT CXSourceRangeList * mojo_clang_getSkippedRanges(CXTranslationUnit tu, CXFile file) {
    return clang_getSkippedRanges(tu, file);
}

MOJO_SHIM_EXPORT CXSourceRangeList * mojo_clang_getAllSkippedRanges(CXTranslationUnit tu) {
    return clang_getAllSkippedRanges(tu);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getNumDiagnostics(CXTranslationUnit Unit) {
    return clang_getNumDiagnostics(Unit);
}

MOJO_SHIM_EXPORT CXDiagnostic mojo_clang_getDiagnostic(CXTranslationUnit Unit, unsigned int Index) {
    return clang_getDiagnostic(Unit, Index);
}

MOJO_SHIM_EXPORT CXDiagnosticSet mojo_clang_getDiagnosticSetFromTU(CXTranslationUnit Unit) {
    return clang_getDiagnosticSetFromTU(Unit);
}

MOJO_SHIM_EXPORT void mojo_clang_getTranslationUnitSpelling(CXString * out, CXTranslationUnit CTUnit) {
    *out = clang_getTranslationUnitSpelling(CTUnit);
}

MOJO_SHIM_EXPORT CXTranslationUnit mojo_clang_createTranslationUnitFromSourceFile(CXIndex CIdx, const char * source_filename, int num_clang_command_line_args, const const char * * clang_command_line_args, unsigned int num_unsaved_files, struct CXUnsavedFile * unsaved_files) {
    return clang_createTranslationUnitFromSourceFile(CIdx, source_filename, num_clang_command_line_args, clang_command_line_args, num_unsaved_files, unsaved_files);
}

MOJO_SHIM_EXPORT CXTranslationUnit mojo_clang_createTranslationUnit(CXIndex CIdx, const char * ast_filename) {
    return clang_createTranslationUnit(CIdx, ast_filename);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_createTranslationUnit2(CXIndex CIdx, const char * ast_filename, CXTranslationUnit * out_TU) {
    return clang_createTranslationUnit2(CIdx, ast_filename, out_TU);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_defaultEditingTranslationUnitOptions(void) {
    return clang_defaultEditingTranslationUnitOptions();
}

MOJO_SHIM_EXPORT CXTranslationUnit mojo_clang_parseTranslationUnit(CXIndex CIdx, const char * source_filename, const const char * * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, unsigned int options) {
    return clang_parseTranslationUnit(CIdx, source_filename, command_line_args, num_command_line_args, unsaved_files, num_unsaved_files, options);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_parseTranslationUnit2(CXIndex CIdx, const char * source_filename, const const char * * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, unsigned int options, CXTranslationUnit * out_TU) {
    return clang_parseTranslationUnit2(CIdx, source_filename, command_line_args, num_command_line_args, unsaved_files, num_unsaved_files, options, out_TU);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_parseTranslationUnit2FullArgv(CXIndex CIdx, const char * source_filename, const const char * * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, unsigned int options, CXTranslationUnit * out_TU) {
    return clang_parseTranslationUnit2FullArgv(CIdx, source_filename, command_line_args, num_command_line_args, unsaved_files, num_unsaved_files, options, out_TU);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_defaultSaveOptions(CXTranslationUnit TU) {
    return clang_defaultSaveOptions(TU);
}

MOJO_SHIM_EXPORT int mojo_clang_saveTranslationUnit(CXTranslationUnit TU, const char * FileName, unsigned int options) {
    return clang_saveTranslationUnit(TU, FileName, options);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_suspendTranslationUnit(CXTranslationUnit arg0) {
    return clang_suspendTranslationUnit(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeTranslationUnit(CXTranslationUnit arg0) {
    clang_disposeTranslationUnit(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_defaultReparseOptions(CXTranslationUnit TU) {
    return clang_defaultReparseOptions(TU);
}

MOJO_SHIM_EXPORT int mojo_clang_reparseTranslationUnit(CXTranslationUnit TU, unsigned int num_unsaved_files, struct CXUnsavedFile * unsaved_files, unsigned int options) {
    return clang_reparseTranslationUnit(TU, num_unsaved_files, unsaved_files, options);
}

MOJO_SHIM_EXPORT const char * mojo_clang_getTUResourceUsageName(enum CXTUResourceUsageKind kind) {
    return clang_getTUResourceUsageName(kind);
}

MOJO_SHIM_EXPORT CXTUResourceUsage mojo_clang_getCXTUResourceUsage(CXTranslationUnit TU) {
    return clang_getCXTUResourceUsage(TU);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeCXTUResourceUsage(CXTUResourceUsage usage) {
    clang_disposeCXTUResourceUsage(usage);
}

MOJO_SHIM_EXPORT CXTargetInfo mojo_clang_getTranslationUnitTargetInfo(CXTranslationUnit CTUnit) {
    return clang_getTranslationUnitTargetInfo(CTUnit);
}

MOJO_SHIM_EXPORT void mojo_clang_TargetInfo_dispose(CXTargetInfo Info) {
    clang_TargetInfo_dispose(Info);
}

MOJO_SHIM_EXPORT void mojo_clang_TargetInfo_getTriple(CXString * out, CXTargetInfo Info) {
    *out = clang_TargetInfo_getTriple(Info);
}

MOJO_SHIM_EXPORT int mojo_clang_TargetInfo_getPointerWidth(CXTargetInfo Info) {
    return clang_TargetInfo_getPointerWidth(Info);
}

MOJO_SHIM_EXPORT void mojo_clang_getNullCursor(CXCursor * out) {
    *out = clang_getNullCursor();
}

MOJO_SHIM_EXPORT void mojo_clang_getTranslationUnitCursor(CXCursor * out, CXTranslationUnit arg1) {
    *out = clang_getTranslationUnitCursor(arg1);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_equalCursors(const CXCursor * arg0, const CXCursor * arg1) {
    return clang_equalCursors(*arg0, *arg1);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_isNull(const CXCursor * cursor) {
    return clang_Cursor_isNull(*cursor);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_hashCursor(const CXCursor * arg0) {
    return clang_hashCursor(*arg0);
}

MOJO_SHIM_EXPORT enum CXCursorKind mojo_clang_getCursorKind(const CXCursor * arg0) {
    return clang_getCursorKind(*arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isDeclaration(enum CXCursorKind arg0) {
    return clang_isDeclaration(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isInvalidDeclaration(const CXCursor * arg0) {
    return clang_isInvalidDeclaration(*arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isReference(enum CXCursorKind arg0) {
    return clang_isReference(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isExpression(enum CXCursorKind arg0) {
    return clang_isExpression(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isStatement(enum CXCursorKind arg0) {
    return clang_isStatement(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isAttribute(enum CXCursorKind arg0) {
    return clang_isAttribute(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_hasAttrs(const CXCursor * C) {
    return clang_Cursor_hasAttrs(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isInvalid(enum CXCursorKind arg0) {
    return clang_isInvalid(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isTranslationUnit(enum CXCursorKind arg0) {
    return clang_isTranslationUnit(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isPreprocessing(enum CXCursorKind arg0) {
    return clang_isPreprocessing(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isUnexposed(enum CXCursorKind arg0) {
    return clang_isUnexposed(arg0);
}

MOJO_SHIM_EXPORT enum CXLinkageKind mojo_clang_getCursorLinkage(const CXCursor * cursor) {
    return clang_getCursorLinkage(*cursor);
}

MOJO_SHIM_EXPORT enum CXVisibilityKind mojo_clang_getCursorVisibility(const CXCursor * cursor) {
    return clang_getCursorVisibility(*cursor);
}

MOJO_SHIM_EXPORT enum CXAvailabilityKind mojo_clang_getCursorAvailability(const CXCursor * cursor) {
    return clang_getCursorAvailability(*cursor);
}

MOJO_SHIM_EXPORT int mojo_clang_getCursorPlatformAvailability(const CXCursor * cursor, int * always_deprecated, CXString * deprecated_message, int * always_unavailable, CXString * unavailable_message, CXPlatformAvailability * availability, int availability_size) {
    return clang_getCursorPlatformAvailability(*cursor, always_deprecated, deprecated_message, always_unavailable, unavailable_message, availability, availability_size);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeCXPlatformAvailability(CXPlatformAvailability * availability) {
    clang_disposeCXPlatformAvailability(availability);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getVarDeclInitializer(CXCursor * out, const CXCursor * cursor) {
    *out = clang_Cursor_getVarDeclInitializer(*cursor);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_hasVarDeclGlobalStorage(const CXCursor * cursor) {
    return clang_Cursor_hasVarDeclGlobalStorage(*cursor);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_hasVarDeclExternalStorage(const CXCursor * cursor) {
    return clang_Cursor_hasVarDeclExternalStorage(*cursor);
}

MOJO_SHIM_EXPORT enum CXLanguageKind mojo_clang_getCursorLanguage(const CXCursor * cursor) {
    return clang_getCursorLanguage(*cursor);
}

MOJO_SHIM_EXPORT enum CXTLSKind mojo_clang_getCursorTLSKind(const CXCursor * cursor) {
    return clang_getCursorTLSKind(*cursor);
}

MOJO_SHIM_EXPORT CXTranslationUnit mojo_clang_Cursor_getTranslationUnit(const CXCursor * arg0) {
    return clang_Cursor_getTranslationUnit(*arg0);
}

MOJO_SHIM_EXPORT CXCursorSet mojo_clang_createCXCursorSet(void) {
    return clang_createCXCursorSet();
}

MOJO_SHIM_EXPORT void mojo_clang_disposeCXCursorSet(CXCursorSet cset) {
    clang_disposeCXCursorSet(cset);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXCursorSet_contains(CXCursorSet cset, const CXCursor * cursor) {
    return clang_CXCursorSet_contains(cset, *cursor);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXCursorSet_insert(CXCursorSet cset, const CXCursor * cursor) {
    return clang_CXCursorSet_insert(cset, *cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorSemanticParent(CXCursor * out, const CXCursor * cursor) {
    *out = clang_getCursorSemanticParent(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorLexicalParent(CXCursor * out, const CXCursor * cursor) {
    *out = clang_getCursorLexicalParent(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getOverriddenCursors(const CXCursor * cursor, CXCursor * * overridden, unsigned int * num_overridden) {
    clang_getOverriddenCursors(*cursor, overridden, num_overridden);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeOverriddenCursors(CXCursor * overridden) {
    clang_disposeOverriddenCursors(overridden);
}

MOJO_SHIM_EXPORT CXFile mojo_clang_getIncludedFile(const CXCursor * cursor) {
    return clang_getIncludedFile(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursor(CXCursor * out, CXTranslationUnit arg1, const CXSourceLocation * arg2) {
    *out = clang_getCursor(arg1, *arg2);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorLocation(CXSourceLocation * out, const CXCursor * arg1) {
    *out = clang_getCursorLocation(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorExtent(CXSourceRange * out, const CXCursor * arg1) {
    *out = clang_getCursorExtent(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorType(CXType * out, const CXCursor * C) {
    *out = clang_getCursorType(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_getTypeSpelling(CXString * out, const CXType * CT) {
    *out = clang_getTypeSpelling(*CT);
}

MOJO_SHIM_EXPORT void mojo_clang_getTypedefDeclUnderlyingType(CXType * out, const CXCursor * C) {
    *out = clang_getTypedefDeclUnderlyingType(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_getEnumDeclIntegerType(CXType * out, const CXCursor * C) {
    *out = clang_getEnumDeclIntegerType(*C);
}

MOJO_SHIM_EXPORT long long mojo_clang_getEnumConstantDeclValue(const CXCursor * C) {
    return clang_getEnumConstantDeclValue(*C);
}

MOJO_SHIM_EXPORT unsigned long long mojo_clang_getEnumConstantDeclUnsignedValue(const CXCursor * C) {
    return clang_getEnumConstantDeclUnsignedValue(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isBitField(const CXCursor * C) {
    return clang_Cursor_isBitField(*C);
}

MOJO_SHIM_EXPORT int mojo_clang_getFieldDeclBitWidth(const CXCursor * C) {
    return clang_getFieldDeclBitWidth(*C);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_getNumArguments(const CXCursor * C) {
    return clang_Cursor_getNumArguments(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getArgument(CXCursor * out, const CXCursor * C, unsigned int i) {
    *out = clang_Cursor_getArgument(*C, i);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_getNumTemplateArguments(const CXCursor * C) {
    return clang_Cursor_getNumTemplateArguments(*C);
}

MOJO_SHIM_EXPORT enum CXTemplateArgumentKind mojo_clang_Cursor_getTemplateArgumentKind(const CXCursor * C, unsigned int I) {
    return clang_Cursor_getTemplateArgumentKind(*C, I);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getTemplateArgumentType(CXType * out, const CXCursor * C, unsigned int I) {
    *out = clang_Cursor_getTemplateArgumentType(*C, I);
}

MOJO_SHIM_EXPORT long long mojo_clang_Cursor_getTemplateArgumentValue(const CXCursor * C, unsigned int I) {
    return clang_Cursor_getTemplateArgumentValue(*C, I);
}

MOJO_SHIM_EXPORT unsigned long long mojo_clang_Cursor_getTemplateArgumentUnsignedValue(const CXCursor * C, unsigned int I) {
    return clang_Cursor_getTemplateArgumentUnsignedValue(*C, I);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_equalTypes(const CXType * A, const CXType * B) {
    return clang_equalTypes(*A, *B);
}

MOJO_SHIM_EXPORT void mojo_clang_getCanonicalType(CXType * out, const CXType * T) {
    *out = clang_getCanonicalType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isConstQualifiedType(const CXType * T) {
    return clang_isConstQualifiedType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isMacroFunctionLike(const CXCursor * C) {
    return clang_Cursor_isMacroFunctionLike(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isMacroBuiltin(const CXCursor * C) {
    return clang_Cursor_isMacroBuiltin(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isFunctionInlined(const CXCursor * C) {
    return clang_Cursor_isFunctionInlined(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isVolatileQualifiedType(const CXType * T) {
    return clang_isVolatileQualifiedType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isRestrictQualifiedType(const CXType * T) {
    return clang_isRestrictQualifiedType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getAddressSpace(const CXType * T) {
    return clang_getAddressSpace(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getTypedefName(CXString * out, const CXType * CT) {
    *out = clang_getTypedefName(*CT);
}

MOJO_SHIM_EXPORT void mojo_clang_getPointeeType(CXType * out, const CXType * T) {
    *out = clang_getPointeeType(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getUnqualifiedType(CXType * out, const CXType * CT) {
    *out = clang_getUnqualifiedType(*CT);
}

MOJO_SHIM_EXPORT void mojo_clang_getNonReferenceType(CXType * out, const CXType * CT) {
    *out = clang_getNonReferenceType(*CT);
}

MOJO_SHIM_EXPORT void mojo_clang_getTypeDeclaration(CXCursor * out, const CXType * T) {
    *out = clang_getTypeDeclaration(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getDeclObjCTypeEncoding(CXString * out, const CXCursor * C) {
    *out = clang_getDeclObjCTypeEncoding(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getObjCEncoding(CXString * out, const CXType * type) {
    *out = clang_Type_getObjCEncoding(*type);
}

MOJO_SHIM_EXPORT void mojo_clang_getTypeKindSpelling(CXString * out, enum CXTypeKind K) {
    *out = clang_getTypeKindSpelling(K);
}

MOJO_SHIM_EXPORT enum CXCallingConv mojo_clang_getFunctionTypeCallingConv(const CXType * T) {
    return clang_getFunctionTypeCallingConv(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getResultType(CXType * out, const CXType * T) {
    *out = clang_getResultType(*T);
}

MOJO_SHIM_EXPORT int mojo_clang_getExceptionSpecificationType(const CXType * T) {
    return clang_getExceptionSpecificationType(*T);
}

MOJO_SHIM_EXPORT int mojo_clang_getNumArgTypes(const CXType * T) {
    return clang_getNumArgTypes(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getArgType(CXType * out, const CXType * T, unsigned int i) {
    *out = clang_getArgType(*T, i);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getObjCObjectBaseType(CXType * out, const CXType * T) {
    *out = clang_Type_getObjCObjectBaseType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Type_getNumObjCProtocolRefs(const CXType * T) {
    return clang_Type_getNumObjCProtocolRefs(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getObjCProtocolDecl(CXCursor * out, const CXType * T, unsigned int i) {
    *out = clang_Type_getObjCProtocolDecl(*T, i);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Type_getNumObjCTypeArgs(const CXType * T) {
    return clang_Type_getNumObjCTypeArgs(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getObjCTypeArg(CXType * out, const CXType * T, unsigned int i) {
    *out = clang_Type_getObjCTypeArg(*T, i);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isFunctionTypeVariadic(const CXType * T) {
    return clang_isFunctionTypeVariadic(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorResultType(CXType * out, const CXCursor * C) {
    *out = clang_getCursorResultType(*C);
}

MOJO_SHIM_EXPORT int mojo_clang_getCursorExceptionSpecificationType(const CXCursor * C) {
    return clang_getCursorExceptionSpecificationType(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isPODType(const CXType * T) {
    return clang_isPODType(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getElementType(CXType * out, const CXType * T) {
    *out = clang_getElementType(*T);
}

MOJO_SHIM_EXPORT long long mojo_clang_getNumElements(const CXType * T) {
    return clang_getNumElements(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_getArrayElementType(CXType * out, const CXType * T) {
    *out = clang_getArrayElementType(*T);
}

MOJO_SHIM_EXPORT long long mojo_clang_getArraySize(const CXType * T) {
    return clang_getArraySize(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getNamedType(CXType * out, const CXType * T) {
    *out = clang_Type_getNamedType(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Type_isTransparentTagTypedef(const CXType * T) {
    return clang_Type_isTransparentTagTypedef(*T);
}

MOJO_SHIM_EXPORT enum CXTypeNullabilityKind mojo_clang_Type_getNullability(const CXType * T) {
    return clang_Type_getNullability(*T);
}

MOJO_SHIM_EXPORT long long mojo_clang_Type_getAlignOf(const CXType * T) {
    return clang_Type_getAlignOf(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getClassType(CXType * out, const CXType * T) {
    *out = clang_Type_getClassType(*T);
}

MOJO_SHIM_EXPORT long long mojo_clang_Type_getSizeOf(const CXType * T) {
    return clang_Type_getSizeOf(*T);
}

MOJO_SHIM_EXPORT long long mojo_clang_Type_getOffsetOf(const CXType * T, const char * S) {
    return clang_Type_getOffsetOf(*T, S);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getModifiedType(CXType * out, const CXType * T) {
    *out = clang_Type_getModifiedType(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getValueType(CXType * out, const CXType * CT) {
    *out = clang_Type_getValueType(*CT);
}

MOJO_SHIM_EXPORT long long mojo_clang_Cursor_getOffsetOfField(const CXCursor * C) {
    return clang_Cursor_getOffsetOfField(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isAnonymous(const CXCursor * C) {
    return clang_Cursor_isAnonymous(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isAnonymousRecordDecl(const CXCursor * C) {
    return clang_Cursor_isAnonymousRecordDecl(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isInlineNamespace(const CXCursor * C) {
    return clang_Cursor_isInlineNamespace(*C);
}

MOJO_SHIM_EXPORT int mojo_clang_Type_getNumTemplateArguments(const CXType * T) {
    return clang_Type_getNumTemplateArguments(*T);
}

MOJO_SHIM_EXPORT void mojo_clang_Type_getTemplateArgumentAsType(CXType * out, const CXType * T, unsigned int i) {
    *out = clang_Type_getTemplateArgumentAsType(*T, i);
}

MOJO_SHIM_EXPORT enum CXRefQualifierKind mojo_clang_Type_getCXXRefQualifier(const CXType * T) {
    return clang_Type_getCXXRefQualifier(*T);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isVirtualBase(const CXCursor * arg0) {
    return clang_isVirtualBase(*arg0);
}

MOJO_SHIM_EXPORT enum CX_CXXAccessSpecifier mojo_clang_getCXXAccessSpecifier(const CXCursor * arg0) {
    return clang_getCXXAccessSpecifier(*arg0);
}

MOJO_SHIM_EXPORT enum CX_StorageClass mojo_clang_Cursor_getStorageClass(const CXCursor * arg0) {
    return clang_Cursor_getStorageClass(*arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getNumOverloadedDecls(const CXCursor * cursor) {
    return clang_getNumOverloadedDecls(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getOverloadedDecl(CXCursor * out, const CXCursor * cursor, unsigned int index) {
    *out = clang_getOverloadedDecl(*cursor, index);
}

MOJO_SHIM_EXPORT void mojo_clang_getIBOutletCollectionType(CXType * out, const CXCursor * arg1) {
    *out = clang_getIBOutletCollectionType(*arg1);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_visitChildren(const CXCursor * parent, enum CXChildVisitResult (*visitor)(const CXCursor * arg0, const CXCursor * arg1, void * arg2), CXClientData client_data) {
    MojoCXCursorVisitorContext ctx = { .fn = visitor, .client_data = client_data };
    return clang_visitChildren(*parent, mojo_CXCursorVisitor_trampoline, &ctx);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_visitChildrenWithBlock(const CXCursor * parent, CXCursorVisitorBlock block) {
    return clang_visitChildrenWithBlock(*parent, block);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorUSR(CXString * out, const CXCursor * arg1) {
    *out = clang_getCursorUSR(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCClass(CXString * out, const char * class_name) {
    *out = clang_constructUSR_ObjCClass(class_name);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCCategory(CXString * out, const char * class_name, const char * category_name) {
    *out = clang_constructUSR_ObjCCategory(class_name, category_name);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCProtocol(CXString * out, const char * protocol_name) {
    *out = clang_constructUSR_ObjCProtocol(protocol_name);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCIvar(CXString * out, const char * name, const CXString * classUSR) {
    *out = clang_constructUSR_ObjCIvar(name, *classUSR);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCMethod(CXString * out, const char * name, unsigned int isInstanceMethod, const CXString * classUSR) {
    *out = clang_constructUSR_ObjCMethod(name, isInstanceMethod, *classUSR);
}

MOJO_SHIM_EXPORT void mojo_clang_constructUSR_ObjCProperty(CXString * out, const char * property, const CXString * classUSR) {
    *out = clang_constructUSR_ObjCProperty(property, *classUSR);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorSpelling(CXString * out, const CXCursor * arg1) {
    *out = clang_getCursorSpelling(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getSpellingNameRange(CXSourceRange * out, const CXCursor * arg1, unsigned int pieceIndex, unsigned int options) {
    *out = clang_Cursor_getSpellingNameRange(*arg1, pieceIndex, options);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_PrintingPolicy_getProperty(CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property) {
    return clang_PrintingPolicy_getProperty(Policy, Property);
}

MOJO_SHIM_EXPORT void mojo_clang_PrintingPolicy_setProperty(CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property, unsigned int Value) {
    clang_PrintingPolicy_setProperty(Policy, Property, Value);
}

MOJO_SHIM_EXPORT CXPrintingPolicy mojo_clang_getCursorPrintingPolicy(const CXCursor * arg0) {
    return clang_getCursorPrintingPolicy(*arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_PrintingPolicy_dispose(CXPrintingPolicy Policy) {
    clang_PrintingPolicy_dispose(Policy);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorPrettyPrinted(CXString * out, const CXCursor * Cursor, CXPrintingPolicy Policy) {
    *out = clang_getCursorPrettyPrinted(*Cursor, Policy);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorDisplayName(CXString * out, const CXCursor * arg1) {
    *out = clang_getCursorDisplayName(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorReferenced(CXCursor * out, const CXCursor * arg1) {
    *out = clang_getCursorReferenced(*arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorDefinition(CXCursor * out, const CXCursor * arg1) {
    *out = clang_getCursorDefinition(*arg1);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_isCursorDefinition(const CXCursor * arg0) {
    return clang_isCursorDefinition(*arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getCanonicalCursor(CXCursor * out, const CXCursor * arg1) {
    *out = clang_getCanonicalCursor(*arg1);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_getObjCSelectorIndex(const CXCursor * arg0) {
    return clang_Cursor_getObjCSelectorIndex(*arg0);
}

MOJO_SHIM_EXPORT int mojo_clang_Cursor_isDynamicCall(const CXCursor * C) {
    return clang_Cursor_isDynamicCall(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getReceiverType(CXType * out, const CXCursor * C) {
    *out = clang_Cursor_getReceiverType(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_getObjCPropertyAttributes(const CXCursor * C, unsigned int reserved) {
    return clang_Cursor_getObjCPropertyAttributes(*C, reserved);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getObjCPropertyGetterName(CXString * out, const CXCursor * C) {
    *out = clang_Cursor_getObjCPropertyGetterName(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getObjCPropertySetterName(CXString * out, const CXCursor * C) {
    *out = clang_Cursor_getObjCPropertySetterName(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_getObjCDeclQualifiers(const CXCursor * C) {
    return clang_Cursor_getObjCDeclQualifiers(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isObjCOptional(const CXCursor * C) {
    return clang_Cursor_isObjCOptional(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isVariadic(const CXCursor * C) {
    return clang_Cursor_isVariadic(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Cursor_isExternalSymbol(const CXCursor * C, CXString * language, CXString * definedIn, unsigned int * isGenerated) {
    return clang_Cursor_isExternalSymbol(*C, language, definedIn, isGenerated);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getCommentRange(CXSourceRange * out, const CXCursor * C) {
    *out = clang_Cursor_getCommentRange(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getRawCommentText(CXString * out, const CXCursor * C) {
    *out = clang_Cursor_getRawCommentText(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getBriefCommentText(CXString * out, const CXCursor * C) {
    *out = clang_Cursor_getBriefCommentText(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getMangling(CXString * out, const CXCursor * arg1) {
    *out = clang_Cursor_getMangling(*arg1);
}

MOJO_SHIM_EXPORT CXStringSet * mojo_clang_Cursor_getCXXManglings(const CXCursor * arg0) {
    return clang_Cursor_getCXXManglings(*arg0);
}

MOJO_SHIM_EXPORT CXStringSet * mojo_clang_Cursor_getObjCManglings(const CXCursor * arg0) {
    return clang_Cursor_getObjCManglings(*arg0);
}

MOJO_SHIM_EXPORT CXModule mojo_clang_Cursor_getModule(const CXCursor * C) {
    return clang_Cursor_getModule(*C);
}

MOJO_SHIM_EXPORT CXModule mojo_clang_getModuleForFile(CXTranslationUnit arg0, CXFile arg1) {
    return clang_getModuleForFile(arg0, arg1);
}

MOJO_SHIM_EXPORT CXFile mojo_clang_Module_getASTFile(CXModule Module) {
    return clang_Module_getASTFile(Module);
}

MOJO_SHIM_EXPORT CXModule mojo_clang_Module_getParent(CXModule Module) {
    return clang_Module_getParent(Module);
}

MOJO_SHIM_EXPORT void mojo_clang_Module_getName(CXString * out, CXModule Module) {
    *out = clang_Module_getName(Module);
}

MOJO_SHIM_EXPORT void mojo_clang_Module_getFullName(CXString * out, CXModule Module) {
    *out = clang_Module_getFullName(Module);
}

MOJO_SHIM_EXPORT int mojo_clang_Module_isSystem(CXModule Module) {
    return clang_Module_isSystem(Module);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Module_getNumTopLevelHeaders(CXTranslationUnit arg0, CXModule Module) {
    return clang_Module_getNumTopLevelHeaders(arg0, Module);
}

MOJO_SHIM_EXPORT CXFile mojo_clang_Module_getTopLevelHeader(CXTranslationUnit arg0, CXModule Module, unsigned int Index) {
    return clang_Module_getTopLevelHeader(arg0, Module, Index);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXConstructor_isConvertingConstructor(const CXCursor * C) {
    return clang_CXXConstructor_isConvertingConstructor(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXConstructor_isCopyConstructor(const CXCursor * C) {
    return clang_CXXConstructor_isCopyConstructor(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXConstructor_isDefaultConstructor(const CXCursor * C) {
    return clang_CXXConstructor_isDefaultConstructor(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXConstructor_isMoveConstructor(const CXCursor * C) {
    return clang_CXXConstructor_isMoveConstructor(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXField_isMutable(const CXCursor * C) {
    return clang_CXXField_isMutable(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isDefaulted(const CXCursor * C) {
    return clang_CXXMethod_isDefaulted(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isDeleted(const CXCursor * C) {
    return clang_CXXMethod_isDeleted(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isPureVirtual(const CXCursor * C) {
    return clang_CXXMethod_isPureVirtual(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isStatic(const CXCursor * C) {
    return clang_CXXMethod_isStatic(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isVirtual(const CXCursor * C) {
    return clang_CXXMethod_isVirtual(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isCopyAssignmentOperator(const CXCursor * C) {
    return clang_CXXMethod_isCopyAssignmentOperator(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isMoveAssignmentOperator(const CXCursor * C) {
    return clang_CXXMethod_isMoveAssignmentOperator(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isExplicit(const CXCursor * C) {
    return clang_CXXMethod_isExplicit(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXRecord_isAbstract(const CXCursor * C) {
    return clang_CXXRecord_isAbstract(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_EnumDecl_isScoped(const CXCursor * C) {
    return clang_EnumDecl_isScoped(*C);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CXXMethod_isConst(const CXCursor * C) {
    return clang_CXXMethod_isConst(*C);
}

MOJO_SHIM_EXPORT enum CXCursorKind mojo_clang_getTemplateCursorKind(const CXCursor * C) {
    return clang_getTemplateCursorKind(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_getSpecializedCursorTemplate(CXCursor * out, const CXCursor * C) {
    *out = clang_getSpecializedCursorTemplate(*C);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorReferenceNameRange(CXSourceRange * out, const CXCursor * C, unsigned int NameFlags, unsigned int PieceIndex) {
    *out = clang_getCursorReferenceNameRange(*C, NameFlags, PieceIndex);
}

MOJO_SHIM_EXPORT CXToken * mojo_clang_getToken(CXTranslationUnit TU, const CXSourceLocation * Location) {
    return clang_getToken(TU, *Location);
}

MOJO_SHIM_EXPORT CXTokenKind mojo_clang_getTokenKind(const CXToken * arg0) {
    return clang_getTokenKind(*arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_getTokenSpelling(CXString * out, CXTranslationUnit arg1, const CXToken * arg2) {
    *out = clang_getTokenSpelling(arg1, *arg2);
}

MOJO_SHIM_EXPORT void mojo_clang_getTokenLocation(CXSourceLocation * out, CXTranslationUnit arg1, const CXToken * arg2) {
    *out = clang_getTokenLocation(arg1, *arg2);
}

MOJO_SHIM_EXPORT void mojo_clang_getTokenExtent(CXSourceRange * out, CXTranslationUnit arg1, const CXToken * arg2) {
    *out = clang_getTokenExtent(arg1, *arg2);
}

MOJO_SHIM_EXPORT void mojo_clang_tokenize(CXTranslationUnit TU, const CXSourceRange * Range, CXToken * * Tokens, unsigned int * NumTokens) {
    clang_tokenize(TU, *Range, Tokens, NumTokens);
}

MOJO_SHIM_EXPORT void mojo_clang_annotateTokens(CXTranslationUnit TU, CXToken * Tokens, unsigned int NumTokens, CXCursor * Cursors) {
    clang_annotateTokens(TU, Tokens, NumTokens, Cursors);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeTokens(CXTranslationUnit TU, CXToken * Tokens, unsigned int NumTokens) {
    clang_disposeTokens(TU, Tokens, NumTokens);
}

MOJO_SHIM_EXPORT void mojo_clang_getCursorKindSpelling(CXString * out, enum CXCursorKind Kind) {
    *out = clang_getCursorKindSpelling(Kind);
}

MOJO_SHIM_EXPORT void mojo_clang_getDefinitionSpellingAndExtent(const CXCursor * arg0, const char * * startBuf, const char * * endBuf, unsigned int * startLine, unsigned int * startColumn, unsigned int * endLine, unsigned int * endColumn) {
    clang_getDefinitionSpellingAndExtent(*arg0, startBuf, endBuf, startLine, startColumn, endLine, endColumn);
}

MOJO_SHIM_EXPORT void mojo_clang_enableStackTraces(void) {
    clang_enableStackTraces();
}

MOJO_SHIM_EXPORT void mojo_clang_executeOnThread(void (*fn)(void * arg0), void * user_data, unsigned int stack_size) {
    clang_executeOnThread(fn, user_data, stack_size);
}

MOJO_SHIM_EXPORT enum CXCompletionChunkKind mojo_clang_getCompletionChunkKind(CXCompletionString completion_string, unsigned int chunk_number) {
    return clang_getCompletionChunkKind(completion_string, chunk_number);
}

MOJO_SHIM_EXPORT void mojo_clang_getCompletionChunkText(CXString * out, CXCompletionString completion_string, unsigned int chunk_number) {
    *out = clang_getCompletionChunkText(completion_string, chunk_number);
}

MOJO_SHIM_EXPORT CXCompletionString mojo_clang_getCompletionChunkCompletionString(CXCompletionString completion_string, unsigned int chunk_number) {
    return clang_getCompletionChunkCompletionString(completion_string, chunk_number);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getNumCompletionChunks(CXCompletionString completion_string) {
    return clang_getNumCompletionChunks(completion_string);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getCompletionPriority(CXCompletionString completion_string) {
    return clang_getCompletionPriority(completion_string);
}

MOJO_SHIM_EXPORT enum CXAvailabilityKind mojo_clang_getCompletionAvailability(CXCompletionString completion_string) {
    return clang_getCompletionAvailability(completion_string);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getCompletionNumAnnotations(CXCompletionString completion_string) {
    return clang_getCompletionNumAnnotations(completion_string);
}

MOJO_SHIM_EXPORT void mojo_clang_getCompletionAnnotation(CXString * out, CXCompletionString completion_string, unsigned int annotation_number) {
    *out = clang_getCompletionAnnotation(completion_string, annotation_number);
}

MOJO_SHIM_EXPORT void mojo_clang_getCompletionParent(CXString * out, CXCompletionString completion_string, enum CXCursorKind * kind) {
    *out = clang_getCompletionParent(completion_string, kind);
}

MOJO_SHIM_EXPORT void mojo_clang_getCompletionBriefComment(CXString * out, CXCompletionString completion_string) {
    *out = clang_getCompletionBriefComment(completion_string);
}

MOJO_SHIM_EXPORT CXCompletionString mojo_clang_getCursorCompletionString(const CXCursor * cursor) {
    return clang_getCursorCompletionString(*cursor);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_getCompletionNumFixIts(CXCodeCompleteResults * results, unsigned int completion_index) {
    return clang_getCompletionNumFixIts(results, completion_index);
}

MOJO_SHIM_EXPORT void mojo_clang_getCompletionFixIt(CXString * out, CXCodeCompleteResults * results, unsigned int completion_index, unsigned int fixit_index, CXSourceRange * replacement_range) {
    *out = clang_getCompletionFixIt(results, completion_index, fixit_index, replacement_range);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_defaultCodeCompleteOptions(void) {
    return clang_defaultCodeCompleteOptions();
}

MOJO_SHIM_EXPORT CXCodeCompleteResults * mojo_clang_codeCompleteAt(CXTranslationUnit TU, const char * complete_filename, unsigned int complete_line, unsigned int complete_column, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, unsigned int options) {
    return clang_codeCompleteAt(TU, complete_filename, complete_line, complete_column, unsaved_files, num_unsaved_files, options);
}

MOJO_SHIM_EXPORT void mojo_clang_sortCodeCompletionResults(CXCompletionResult * Results, unsigned int NumResults) {
    clang_sortCodeCompletionResults(Results, NumResults);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeCodeCompleteResults(CXCodeCompleteResults * Results) {
    clang_disposeCodeCompleteResults(Results);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_codeCompleteGetNumDiagnostics(CXCodeCompleteResults * Results) {
    return clang_codeCompleteGetNumDiagnostics(Results);
}

MOJO_SHIM_EXPORT CXDiagnostic mojo_clang_codeCompleteGetDiagnostic(CXCodeCompleteResults * Results, unsigned int Index) {
    return clang_codeCompleteGetDiagnostic(Results, Index);
}

MOJO_SHIM_EXPORT unsigned long long mojo_clang_codeCompleteGetContexts(CXCodeCompleteResults * Results) {
    return clang_codeCompleteGetContexts(Results);
}

MOJO_SHIM_EXPORT enum CXCursorKind mojo_clang_codeCompleteGetContainerKind(CXCodeCompleteResults * Results, unsigned int * IsIncomplete) {
    return clang_codeCompleteGetContainerKind(Results, IsIncomplete);
}

MOJO_SHIM_EXPORT void mojo_clang_codeCompleteGetContainerUSR(CXString * out, CXCodeCompleteResults * Results) {
    *out = clang_codeCompleteGetContainerUSR(Results);
}

MOJO_SHIM_EXPORT void mojo_clang_codeCompleteGetObjCSelector(CXString * out, CXCodeCompleteResults * Results) {
    *out = clang_codeCompleteGetObjCSelector(Results);
}

MOJO_SHIM_EXPORT void mojo_clang_getClangVersion(CXString * out) {
    *out = clang_getClangVersion();
}

MOJO_SHIM_EXPORT void mojo_clang_toggleCrashRecovery(unsigned int isEnabled) {
    clang_toggleCrashRecovery(isEnabled);
}

MOJO_SHIM_EXPORT void mojo_clang_getInclusions(CXTranslationUnit tu, void (*visitor)(void * arg0, CXSourceLocation * arg1, unsigned int arg2, void * arg3), CXClientData client_data) {
    clang_getInclusions(tu, visitor, client_data);
}

MOJO_SHIM_EXPORT CXEvalResult mojo_clang_Cursor_Evaluate(const CXCursor * C) {
    return clang_Cursor_Evaluate(*C);
}

MOJO_SHIM_EXPORT CXEvalResultKind mojo_clang_EvalResult_getKind(CXEvalResult E) {
    return clang_EvalResult_getKind(E);
}

MOJO_SHIM_EXPORT int mojo_clang_EvalResult_getAsInt(CXEvalResult E) {
    return clang_EvalResult_getAsInt(E);
}

MOJO_SHIM_EXPORT long long mojo_clang_EvalResult_getAsLongLong(CXEvalResult E) {
    return clang_EvalResult_getAsLongLong(E);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_EvalResult_isUnsignedInt(CXEvalResult E) {
    return clang_EvalResult_isUnsignedInt(E);
}

MOJO_SHIM_EXPORT unsigned long long mojo_clang_EvalResult_getAsUnsigned(CXEvalResult E) {
    return clang_EvalResult_getAsUnsigned(E);
}

MOJO_SHIM_EXPORT double mojo_clang_EvalResult_getAsDouble(CXEvalResult E) {
    return clang_EvalResult_getAsDouble(E);
}

MOJO_SHIM_EXPORT const char * mojo_clang_EvalResult_getAsStr(CXEvalResult E) {
    return clang_EvalResult_getAsStr(E);
}

MOJO_SHIM_EXPORT void mojo_clang_EvalResult_dispose(CXEvalResult E) {
    clang_EvalResult_dispose(E);
}

MOJO_SHIM_EXPORT CXRemapping mojo_clang_getRemappings(const char * path) {
    return clang_getRemappings(path);
}

MOJO_SHIM_EXPORT CXRemapping mojo_clang_getRemappingsFromFileList(const char * * filePaths, unsigned int numFiles) {
    return clang_getRemappingsFromFileList(filePaths, numFiles);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_remap_getNumFiles(CXRemapping arg0) {
    return clang_remap_getNumFiles(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_remap_getFilenames(CXRemapping arg0, unsigned int index, CXString * original, CXString * transformed) {
    clang_remap_getFilenames(arg0, index, original, transformed);
}

MOJO_SHIM_EXPORT void mojo_clang_remap_dispose(CXRemapping arg0) {
    clang_remap_dispose(arg0);
}

MOJO_SHIM_EXPORT CXResult mojo_clang_findReferencesInFile(const CXCursor * cursor, CXFile file, const CXCursorAndRangeVisitor * visitor) {
    MojoCXCursorAndRangeVisitorContext visitor_ctx = { .visitor = visitor };
    CXCursorAndRangeVisitor normalized_visitor = {
        .context = &visitor_ctx,
        .visit = mojo_CXCursorAndRangeVisitor_trampoline,
    };
    return clang_findReferencesInFile(*cursor, file, normalized_visitor);
}

MOJO_SHIM_EXPORT CXResult mojo_clang_findIncludesInFile(CXTranslationUnit TU, CXFile file, const CXCursorAndRangeVisitor * visitor) {
    MojoCXCursorAndRangeVisitorContext visitor_ctx = { .visitor = visitor };
    CXCursorAndRangeVisitor normalized_visitor = {
        .context = &visitor_ctx,
        .visit = mojo_CXCursorAndRangeVisitor_trampoline,
    };
    return clang_findIncludesInFile(TU, file, normalized_visitor);
}

MOJO_SHIM_EXPORT CXResult mojo_clang_findReferencesInFileWithBlock(const CXCursor * arg0, CXFile arg1, CXCursorAndRangeVisitorBlock arg2) {
    return clang_findReferencesInFileWithBlock(*arg0, arg1, arg2);
}

MOJO_SHIM_EXPORT CXResult mojo_clang_findIncludesInFileWithBlock(CXTranslationUnit arg0, CXFile arg1, CXCursorAndRangeVisitorBlock arg2) {
    return clang_findIncludesInFileWithBlock(arg0, arg1, arg2);
}

MOJO_SHIM_EXPORT int mojo_clang_index_isEntityObjCContainerKind(CXIdxEntityKind arg0) {
    return clang_index_isEntityObjCContainerKind(arg0);
}

MOJO_SHIM_EXPORT const CXIdxObjCContainerDeclInfo * mojo_clang_index_getObjCContainerDeclInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getObjCContainerDeclInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxObjCInterfaceDeclInfo * mojo_clang_index_getObjCInterfaceDeclInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getObjCInterfaceDeclInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxObjCCategoryDeclInfo * mojo_clang_index_getObjCCategoryDeclInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getObjCCategoryDeclInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxObjCProtocolRefListInfo * mojo_clang_index_getObjCProtocolRefListInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getObjCProtocolRefListInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxObjCPropertyDeclInfo * mojo_clang_index_getObjCPropertyDeclInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getObjCPropertyDeclInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxIBOutletCollectionAttrInfo * mojo_clang_index_getIBOutletCollectionAttrInfo(const CXIdxAttrInfo * arg0) {
    return clang_index_getIBOutletCollectionAttrInfo(arg0);
}

MOJO_SHIM_EXPORT const CXIdxCXXClassDeclInfo * mojo_clang_index_getCXXClassDeclInfo(const CXIdxDeclInfo * arg0) {
    return clang_index_getCXXClassDeclInfo(arg0);
}

MOJO_SHIM_EXPORT CXIdxClientContainer mojo_clang_index_getClientContainer(const CXIdxContainerInfo * arg0) {
    return clang_index_getClientContainer(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_index_setClientContainer(const CXIdxContainerInfo * arg0, CXIdxClientContainer arg1) {
    clang_index_setClientContainer(arg0, arg1);
}

MOJO_SHIM_EXPORT CXIdxClientEntity mojo_clang_index_getClientEntity(const CXIdxEntityInfo * arg0) {
    return clang_index_getClientEntity(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_index_setClientEntity(const CXIdxEntityInfo * arg0, CXIdxClientEntity arg1) {
    clang_index_setClientEntity(arg0, arg1);
}

MOJO_SHIM_EXPORT CXIndexAction mojo_clang_IndexAction_create(CXIndex CIdx) {
    return clang_IndexAction_create(CIdx);
}

MOJO_SHIM_EXPORT void mojo_clang_IndexAction_dispose(CXIndexAction arg0) {
    clang_IndexAction_dispose(arg0);
}

MOJO_SHIM_EXPORT int mojo_clang_indexSourceFile(CXIndexAction arg0, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned int index_callbacks_size, unsigned int index_options, const char * source_filename, const const char * * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, CXTranslationUnit * out_TU, unsigned int TU_options) {
    return clang_indexSourceFile(arg0, client_data, index_callbacks, index_callbacks_size, index_options, source_filename, command_line_args, num_command_line_args, unsaved_files, num_unsaved_files, out_TU, TU_options);
}

MOJO_SHIM_EXPORT int mojo_clang_indexSourceFileFullArgv(CXIndexAction arg0, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned int index_callbacks_size, unsigned int index_options, const char * source_filename, const const char * * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned int num_unsaved_files, CXTranslationUnit * out_TU, unsigned int TU_options) {
    return clang_indexSourceFileFullArgv(arg0, client_data, index_callbacks, index_callbacks_size, index_options, source_filename, command_line_args, num_command_line_args, unsaved_files, num_unsaved_files, out_TU, TU_options);
}

MOJO_SHIM_EXPORT int mojo_clang_indexTranslationUnit(CXIndexAction arg0, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned int index_callbacks_size, unsigned int index_options, CXTranslationUnit arg5) {
    return clang_indexTranslationUnit(arg0, client_data, index_callbacks, index_callbacks_size, index_options, arg5);
}

MOJO_SHIM_EXPORT void mojo_clang_indexLoc_getFileLocation(const CXIdxLoc * loc, CXIdxClientFile * indexFile, CXFile * file, unsigned int * line, unsigned int * column, unsigned int * offset) {
    clang_indexLoc_getFileLocation(*loc, indexFile, file, line, column, offset);
}

MOJO_SHIM_EXPORT void mojo_clang_indexLoc_getCXSourceLocation(CXSourceLocation * out, const CXIdxLoc * loc) {
    *out = clang_indexLoc_getCXSourceLocation(*loc);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Type_visitFields(const CXType * T, enum CXVisitorResult (*visitor)(const CXCursor * arg0, void * arg1), CXClientData client_data) {
    MojoCXFieldVisitorContext ctx = { .fn = visitor, .client_data = client_data };
    return clang_Type_visitFields(*T, mojo_CXFieldVisitor_trampoline, &ctx);
}

MOJO_SHIM_EXPORT void mojo_clang_getBinaryOperatorKindSpelling(CXString * out, enum CXBinaryOperatorKind kind) {
    *out = clang_getBinaryOperatorKindSpelling(kind);
}

MOJO_SHIM_EXPORT enum CXBinaryOperatorKind mojo_clang_getCursorBinaryOperatorKind(const CXCursor * cursor) {
    return clang_getCursorBinaryOperatorKind(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_getUnaryOperatorKindSpelling(CXString * out, enum CXUnaryOperatorKind kind) {
    *out = clang_getUnaryOperatorKindSpelling(kind);
}

MOJO_SHIM_EXPORT enum CXUnaryOperatorKind mojo_clang_getCursorUnaryOperatorKind(const CXCursor * cursor) {
    return clang_getCursorUnaryOperatorKind(*cursor);
}

MOJO_SHIM_EXPORT void mojo_clang_Cursor_getParsedComment(CXComment * out, const CXCursor * C) {
    *out = clang_Cursor_getParsedComment(*C);
}

MOJO_SHIM_EXPORT enum CXCommentKind mojo_clang_Comment_getKind(const CXComment * Comment) {
    return clang_Comment_getKind(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Comment_getNumChildren(const CXComment * Comment) {
    return clang_Comment_getNumChildren(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_Comment_getChild(CXComment * out, const CXComment * Comment, unsigned int ChildIdx) {
    *out = clang_Comment_getChild(*Comment, ChildIdx);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_Comment_isWhitespace(const CXComment * Comment) {
    return clang_Comment_isWhitespace(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_InlineContentComment_hasTrailingNewline(const CXComment * Comment) {
    return clang_InlineContentComment_hasTrailingNewline(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_TextComment_getText(CXString * out, const CXComment * Comment) {
    *out = clang_TextComment_getText(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_InlineCommandComment_getCommandName(CXString * out, const CXComment * Comment) {
    *out = clang_InlineCommandComment_getCommandName(*Comment);
}

MOJO_SHIM_EXPORT enum CXCommentInlineCommandRenderKind mojo_clang_InlineCommandComment_getRenderKind(const CXComment * Comment) {
    return clang_InlineCommandComment_getRenderKind(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_InlineCommandComment_getNumArgs(const CXComment * Comment) {
    return clang_InlineCommandComment_getNumArgs(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_InlineCommandComment_getArgText(CXString * out, const CXComment * Comment, unsigned int ArgIdx) {
    *out = clang_InlineCommandComment_getArgText(*Comment, ArgIdx);
}

MOJO_SHIM_EXPORT void mojo_clang_HTMLTagComment_getTagName(CXString * out, const CXComment * Comment) {
    *out = clang_HTMLTagComment_getTagName(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_HTMLStartTagComment_isSelfClosing(const CXComment * Comment) {
    return clang_HTMLStartTagComment_isSelfClosing(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_HTMLStartTag_getNumAttrs(const CXComment * Comment) {
    return clang_HTMLStartTag_getNumAttrs(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_HTMLStartTag_getAttrName(CXString * out, const CXComment * Comment, unsigned int AttrIdx) {
    *out = clang_HTMLStartTag_getAttrName(*Comment, AttrIdx);
}

MOJO_SHIM_EXPORT void mojo_clang_HTMLStartTag_getAttrValue(CXString * out, const CXComment * Comment, unsigned int AttrIdx) {
    *out = clang_HTMLStartTag_getAttrValue(*Comment, AttrIdx);
}

MOJO_SHIM_EXPORT void mojo_clang_BlockCommandComment_getCommandName(CXString * out, const CXComment * Comment) {
    *out = clang_BlockCommandComment_getCommandName(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_BlockCommandComment_getNumArgs(const CXComment * Comment) {
    return clang_BlockCommandComment_getNumArgs(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_BlockCommandComment_getArgText(CXString * out, const CXComment * Comment, unsigned int ArgIdx) {
    *out = clang_BlockCommandComment_getArgText(*Comment, ArgIdx);
}

MOJO_SHIM_EXPORT void mojo_clang_BlockCommandComment_getParagraph(CXComment * out, const CXComment * Comment) {
    *out = clang_BlockCommandComment_getParagraph(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_ParamCommandComment_getParamName(CXString * out, const CXComment * Comment) {
    *out = clang_ParamCommandComment_getParamName(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_ParamCommandComment_isParamIndexValid(const CXComment * Comment) {
    return clang_ParamCommandComment_isParamIndexValid(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_ParamCommandComment_getParamIndex(const CXComment * Comment) {
    return clang_ParamCommandComment_getParamIndex(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_ParamCommandComment_isDirectionExplicit(const CXComment * Comment) {
    return clang_ParamCommandComment_isDirectionExplicit(*Comment);
}

MOJO_SHIM_EXPORT enum CXCommentParamPassDirection mojo_clang_ParamCommandComment_getDirection(const CXComment * Comment) {
    return clang_ParamCommandComment_getDirection(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_TParamCommandComment_getParamName(CXString * out, const CXComment * Comment) {
    *out = clang_TParamCommandComment_getParamName(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_TParamCommandComment_isParamPositionValid(const CXComment * Comment) {
    return clang_TParamCommandComment_isParamPositionValid(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_TParamCommandComment_getDepth(const CXComment * Comment) {
    return clang_TParamCommandComment_getDepth(*Comment);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_TParamCommandComment_getIndex(const CXComment * Comment, unsigned int Depth) {
    return clang_TParamCommandComment_getIndex(*Comment, Depth);
}

MOJO_SHIM_EXPORT void mojo_clang_VerbatimBlockLineComment_getText(CXString * out, const CXComment * Comment) {
    *out = clang_VerbatimBlockLineComment_getText(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_VerbatimLineComment_getText(CXString * out, const CXComment * Comment) {
    *out = clang_VerbatimLineComment_getText(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_HTMLTagComment_getAsString(CXString * out, const CXComment * Comment) {
    *out = clang_HTMLTagComment_getAsString(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_FullComment_getAsHTML(CXString * out, const CXComment * Comment) {
    *out = clang_FullComment_getAsHTML(*Comment);
}

MOJO_SHIM_EXPORT void mojo_clang_FullComment_getAsXML(CXString * out, const CXComment * Comment) {
    *out = clang_FullComment_getAsXML(*Comment);
}

MOJO_SHIM_EXPORT enum CXErrorCode mojo_clang_createAPISet(CXTranslationUnit tu, CXAPISet * out_api) {
    return clang_createAPISet(tu, out_api);
}

MOJO_SHIM_EXPORT void mojo_clang_disposeAPISet(CXAPISet api) {
    clang_disposeAPISet(api);
}

MOJO_SHIM_EXPORT void mojo_clang_getSymbolGraphForUSR(CXString * out, const char * usr, CXAPISet api) {
    *out = clang_getSymbolGraphForUSR(usr, api);
}

MOJO_SHIM_EXPORT void mojo_clang_getSymbolGraphForCursor(CXString * out, const CXCursor * cursor) {
    *out = clang_getSymbolGraphForCursor(*cursor);
}

MOJO_SHIM_EXPORT CXCompilationDatabase mojo_clang_CompilationDatabase_fromDirectory(const char * BuildDir, CXCompilationDatabase_Error * ErrorCode) {
    return clang_CompilationDatabase_fromDirectory(BuildDir, ErrorCode);
}

MOJO_SHIM_EXPORT void mojo_clang_CompilationDatabase_dispose(CXCompilationDatabase arg0) {
    clang_CompilationDatabase_dispose(arg0);
}

MOJO_SHIM_EXPORT CXCompileCommands mojo_clang_CompilationDatabase_getCompileCommands(CXCompilationDatabase arg0, const char * CompleteFileName) {
    return clang_CompilationDatabase_getCompileCommands(arg0, CompleteFileName);
}

MOJO_SHIM_EXPORT CXCompileCommands mojo_clang_CompilationDatabase_getAllCompileCommands(CXCompilationDatabase arg0) {
    return clang_CompilationDatabase_getAllCompileCommands(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommands_dispose(CXCompileCommands arg0) {
    clang_CompileCommands_dispose(arg0);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CompileCommands_getSize(CXCompileCommands arg0) {
    return clang_CompileCommands_getSize(arg0);
}

MOJO_SHIM_EXPORT CXCompileCommand mojo_clang_CompileCommands_getCommand(CXCompileCommands arg0, unsigned int I) {
    return clang_CompileCommands_getCommand(arg0, I);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommand_getDirectory(CXString * out, CXCompileCommand arg1) {
    *out = clang_CompileCommand_getDirectory(arg1);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommand_getFilename(CXString * out, CXCompileCommand arg1) {
    *out = clang_CompileCommand_getFilename(arg1);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CompileCommand_getNumArgs(CXCompileCommand arg0) {
    return clang_CompileCommand_getNumArgs(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommand_getArg(CXString * out, CXCompileCommand arg1, unsigned int I) {
    *out = clang_CompileCommand_getArg(arg1, I);
}

MOJO_SHIM_EXPORT unsigned int mojo_clang_CompileCommand_getNumMappedSources(CXCompileCommand arg0) {
    return clang_CompileCommand_getNumMappedSources(arg0);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommand_getMappedSourcePath(CXString * out, CXCompileCommand arg1, unsigned int I) {
    *out = clang_CompileCommand_getMappedSourcePath(arg1, I);
}

MOJO_SHIM_EXPORT void mojo_clang_CompileCommand_getMappedSourceContent(CXString * out, CXCompileCommand arg1, unsigned int I) {
    *out = clang_CompileCommand_getMappedSourceContent(arg1, I);
}

MOJO_SHIM_EXPORT CXRewriter mojo_clang_CXRewriter_create(CXTranslationUnit TU) {
    return clang_CXRewriter_create(TU);
}

MOJO_SHIM_EXPORT void mojo_clang_CXRewriter_insertTextBefore(CXRewriter Rew, const CXSourceLocation * Loc, const char * Insert) {
    clang_CXRewriter_insertTextBefore(Rew, *Loc, Insert);
}

MOJO_SHIM_EXPORT void mojo_clang_CXRewriter_replaceText(CXRewriter Rew, const CXSourceRange * ToBeReplaced, const char * Replacement) {
    clang_CXRewriter_replaceText(Rew, *ToBeReplaced, Replacement);
}

MOJO_SHIM_EXPORT void mojo_clang_CXRewriter_removeText(CXRewriter Rew, const CXSourceRange * ToBeRemoved) {
    clang_CXRewriter_removeText(Rew, *ToBeRemoved);
}

MOJO_SHIM_EXPORT int mojo_clang_CXRewriter_overwriteChangedFiles(CXRewriter Rew) {
    return clang_CXRewriter_overwriteChangedFiles(Rew);
}

MOJO_SHIM_EXPORT void mojo_clang_CXRewriter_writeMainFileToStdOut(CXRewriter Rew) {
    clang_CXRewriter_writeMainFileToStdOut(Rew);
}

MOJO_SHIM_EXPORT void mojo_clang_CXRewriter_dispose(CXRewriter Rew) {
    clang_CXRewriter_dispose(Rew);
}

MOJO_SHIM_EXPORT void mojo_clang_install_aborting_llvm_fatal_error_handler(void) {
    clang_install_aborting_llvm_fatal_error_handler();
}

MOJO_SHIM_EXPORT void mojo_clang_uninstall_llvm_fatal_error_handler(void) {
    clang_uninstall_llvm_fatal_error_handler();
}
