# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: libclang_raw

from std.testing import TestSuite
from std.sys.info import align_of, size_of
from std.reflection import reflect
from libclang_raw import CXString, CXStringSet, CXFileUniqueID, CXSourceLocation, CXSourceRange, CXSourceRangeList, CXUnsavedFile, CXVersion, CXIndexOptions, CXTUResourceUsageEntry, CXTUResourceUsage, CXCursor, CXPlatformAvailability, CXType, CXToken, CXCompletionResult, CXCodeCompleteResults, CXCursorAndRangeVisitor, CXIdxLoc, CXIdxIncludedFileInfo, CXIdxImportedASTFileInfo, CXIdxAttrInfo, CXIdxEntityInfo, CXIdxContainerInfo, CXIdxIBOutletCollectionAttrInfo, CXIdxDeclInfo, CXIdxObjCContainerDeclInfo, CXIdxBaseClassInfo, CXIdxObjCProtocolRefInfo, CXIdxObjCProtocolRefListInfo, CXIdxObjCInterfaceDeclInfo, CXIdxObjCCategoryDeclInfo, CXIdxObjCPropertyDeclInfo, CXIdxCXXClassDeclInfo, CXIdxEntityRefInfo, IndexerCallbacks, CXComment


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_CXString() raises:
    comptime r = reflect[CXString]()
    _check_eq("CXString.size", Int(size_of[CXString]()), 16)
    _check_eq("CXString.align", Int(align_of[CXString]()), 8)
    _check_eq("CXString.data.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXString.private_flags.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXStringSet() raises:
    comptime r = reflect[CXStringSet]()
    _check_eq("CXStringSet.size", Int(size_of[CXStringSet]()), 16)
    _check_eq("CXStringSet.align", Int(align_of[CXStringSet]()), 8)
    _check_eq("CXStringSet.Strings.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXStringSet.Count.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXFileUniqueID() raises:
    comptime r = reflect[CXFileUniqueID]()
    _check_eq("CXFileUniqueID.size", Int(size_of[CXFileUniqueID]()), 24)
    _check_eq("CXFileUniqueID.align", Int(align_of[CXFileUniqueID]()), 8)
    _check_eq("CXFileUniqueID.data.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_CXSourceLocation() raises:
    comptime r = reflect[CXSourceLocation]()
    _check_eq("CXSourceLocation.size", Int(size_of[CXSourceLocation]()), 24)
    _check_eq("CXSourceLocation.align", Int(align_of[CXSourceLocation]()), 8)
    _check_eq("CXSourceLocation.ptr_data0.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXSourceLocation.ptr_data1.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXSourceLocation.int_data.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXSourceRange() raises:
    comptime r = reflect[CXSourceRange]()
    _check_eq("CXSourceRange.size", Int(size_of[CXSourceRange]()), 24)
    _check_eq("CXSourceRange.align", Int(align_of[CXSourceRange]()), 8)
    _check_eq("CXSourceRange.ptr_data0.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXSourceRange.ptr_data1.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXSourceRange.begin_int_data.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("CXSourceRange.end_int_data.offset", Int(r.field_offset[index=3]()), 20)


def test_layout_CXSourceRangeList() raises:
    comptime r = reflect[CXSourceRangeList]()
    _check_eq("CXSourceRangeList.size", Int(size_of[CXSourceRangeList]()), 16)
    _check_eq("CXSourceRangeList.align", Int(align_of[CXSourceRangeList]()), 8)
    _check_eq("CXSourceRangeList.count.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXSourceRangeList.ranges.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXUnsavedFile() raises:
    comptime r = reflect[CXUnsavedFile]()
    _check_eq("CXUnsavedFile.size", Int(size_of[CXUnsavedFile]()), 24)
    _check_eq("CXUnsavedFile.align", Int(align_of[CXUnsavedFile]()), 8)
    _check_eq("CXUnsavedFile.Filename.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXUnsavedFile.Contents.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXUnsavedFile.Length.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXVersion() raises:
    comptime r = reflect[CXVersion]()
    _check_eq("CXVersion.size", Int(size_of[CXVersion]()), 12)
    _check_eq("CXVersion.align", Int(align_of[CXVersion]()), 4)
    _check_eq("CXVersion.Major.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXVersion.Minor.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("CXVersion.Subminor.offset", Int(r.field_offset[index=2]()), 8)


def test_layout_CXIndexOptions() raises:
    comptime r = reflect[CXIndexOptions]()
    _check_eq("CXIndexOptions.size", Int(size_of[CXIndexOptions]()), 24)
    _check_eq("CXIndexOptions.align", Int(align_of[CXIndexOptions]()), 8)


def test_layout_CXTUResourceUsageEntry() raises:
    comptime r = reflect[CXTUResourceUsageEntry]()
    _check_eq("CXTUResourceUsageEntry.size", Int(size_of[CXTUResourceUsageEntry]()), 16)
    _check_eq("CXTUResourceUsageEntry.align", Int(align_of[CXTUResourceUsageEntry]()), 8)
    _check_eq("CXTUResourceUsageEntry.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXTUResourceUsageEntry.amount.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXTUResourceUsage() raises:
    comptime r = reflect[CXTUResourceUsage]()
    _check_eq("CXTUResourceUsage.size", Int(size_of[CXTUResourceUsage]()), 24)
    _check_eq("CXTUResourceUsage.align", Int(align_of[CXTUResourceUsage]()), 8)
    _check_eq("CXTUResourceUsage.data.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXTUResourceUsage.numEntries.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXTUResourceUsage.entries.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXCursor() raises:
    comptime r = reflect[CXCursor]()
    _check_eq("CXCursor.size", Int(size_of[CXCursor]()), 32)
    _check_eq("CXCursor.align", Int(align_of[CXCursor]()), 8)
    _check_eq("CXCursor.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXCursor.xdata.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("CXCursor.data0.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("CXCursor.data1.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("CXCursor.data2.offset", Int(r.field_offset[index=4]()), 24)


def test_layout_CXPlatformAvailability() raises:
    comptime r = reflect[CXPlatformAvailability]()
    _check_eq("CXPlatformAvailability.size", Int(size_of[CXPlatformAvailability]()), 72)
    _check_eq("CXPlatformAvailability.align", Int(align_of[CXPlatformAvailability]()), 8)
    _check_eq("CXPlatformAvailability.Platform.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXPlatformAvailability.Introduced.offset", Int(r.field_offset[index=1]()), 16)
    _check_eq("CXPlatformAvailability.Deprecated.offset", Int(r.field_offset[index=2]()), 28)
    _check_eq("CXPlatformAvailability.Obsoleted.offset", Int(r.field_offset[index=3]()), 40)
    _check_eq("CXPlatformAvailability.Unavailable.offset", Int(r.field_offset[index=4]()), 52)
    _check_eq("CXPlatformAvailability.Message.offset", Int(r.field_offset[index=5]()), 56)


def test_layout_CXType() raises:
    comptime r = reflect[CXType]()
    _check_eq("CXType.size", Int(size_of[CXType]()), 24)
    _check_eq("CXType.align", Int(align_of[CXType]()), 8)
    _check_eq("CXType.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXType.data0.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXType.data1.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXToken() raises:
    comptime r = reflect[CXToken]()
    _check_eq("CXToken.size", Int(size_of[CXToken]()), 24)
    _check_eq("CXToken.align", Int(align_of[CXToken]()), 8)
    _check_eq("CXToken.int_data0.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXToken.int_data1.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("CXToken.int_data2.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("CXToken.int_data3.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("CXToken.ptr_data.offset", Int(r.field_offset[index=4]()), 16)


def test_layout_CXCompletionResult() raises:
    comptime r = reflect[CXCompletionResult]()
    _check_eq("CXCompletionResult.size", Int(size_of[CXCompletionResult]()), 16)
    _check_eq("CXCompletionResult.align", Int(align_of[CXCompletionResult]()), 8)
    _check_eq("CXCompletionResult.CursorKind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXCompletionResult.CompletionString.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXCodeCompleteResults() raises:
    comptime r = reflect[CXCodeCompleteResults]()
    _check_eq("CXCodeCompleteResults.size", Int(size_of[CXCodeCompleteResults]()), 16)
    _check_eq("CXCodeCompleteResults.align", Int(align_of[CXCodeCompleteResults]()), 8)
    _check_eq("CXCodeCompleteResults.Results.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXCodeCompleteResults.NumResults.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXCursorAndRangeVisitor() raises:
    comptime r = reflect[CXCursorAndRangeVisitor]()
    _check_eq("CXCursorAndRangeVisitor.size", Int(size_of[CXCursorAndRangeVisitor]()), 16)
    _check_eq("CXCursorAndRangeVisitor.align", Int(align_of[CXCursorAndRangeVisitor]()), 8)
    _check_eq("CXCursorAndRangeVisitor.context.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXCursorAndRangeVisitor.visit.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXIdxLoc() raises:
    comptime r = reflect[CXIdxLoc]()
    _check_eq("CXIdxLoc.size", Int(size_of[CXIdxLoc]()), 24)
    _check_eq("CXIdxLoc.align", Int(align_of[CXIdxLoc]()), 8)
    _check_eq("CXIdxLoc.ptr_data0.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxLoc.ptr_data1.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxLoc.int_data.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXIdxIncludedFileInfo() raises:
    comptime r = reflect[CXIdxIncludedFileInfo]()
    _check_eq("CXIdxIncludedFileInfo.size", Int(size_of[CXIdxIncludedFileInfo]()), 56)
    _check_eq("CXIdxIncludedFileInfo.align", Int(align_of[CXIdxIncludedFileInfo]()), 8)
    _check_eq("CXIdxIncludedFileInfo.hashLoc.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxIncludedFileInfo.filename.offset", Int(r.field_offset[index=1]()), 24)
    _check_eq("CXIdxIncludedFileInfo.file.offset", Int(r.field_offset[index=2]()), 32)
    _check_eq("CXIdxIncludedFileInfo.isImport.offset", Int(r.field_offset[index=3]()), 40)
    _check_eq("CXIdxIncludedFileInfo.isAngled.offset", Int(r.field_offset[index=4]()), 44)
    _check_eq("CXIdxIncludedFileInfo.isModuleImport.offset", Int(r.field_offset[index=5]()), 48)


def test_layout_CXIdxImportedASTFileInfo() raises:
    comptime r = reflect[CXIdxImportedASTFileInfo]()
    _check_eq("CXIdxImportedASTFileInfo.size", Int(size_of[CXIdxImportedASTFileInfo]()), 48)
    _check_eq("CXIdxImportedASTFileInfo.align", Int(align_of[CXIdxImportedASTFileInfo]()), 8)
    _check_eq("CXIdxImportedASTFileInfo.file.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxImportedASTFileInfo.module.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxImportedASTFileInfo.loc.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("CXIdxImportedASTFileInfo.isImplicit.offset", Int(r.field_offset[index=3]()), 40)


def test_layout_CXIdxAttrInfo() raises:
    comptime r = reflect[CXIdxAttrInfo]()
    _check_eq("CXIdxAttrInfo.size", Int(size_of[CXIdxAttrInfo]()), 64)
    _check_eq("CXIdxAttrInfo.align", Int(align_of[CXIdxAttrInfo]()), 8)
    _check_eq("CXIdxAttrInfo.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxAttrInfo.cursor.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxAttrInfo.loc.offset", Int(r.field_offset[index=2]()), 40)


def test_layout_CXIdxEntityInfo() raises:
    comptime r = reflect[CXIdxEntityInfo]()
    _check_eq("CXIdxEntityInfo.size", Int(size_of[CXIdxEntityInfo]()), 80)
    _check_eq("CXIdxEntityInfo.align", Int(align_of[CXIdxEntityInfo]()), 8)
    _check_eq("CXIdxEntityInfo.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxEntityInfo.templateKind.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("CXIdxEntityInfo.lang.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("CXIdxEntityInfo.name.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("CXIdxEntityInfo.USR.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("CXIdxEntityInfo.cursor.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("CXIdxEntityInfo.attributes.offset", Int(r.field_offset[index=6]()), 64)
    _check_eq("CXIdxEntityInfo.numAttributes.offset", Int(r.field_offset[index=7]()), 72)


def test_layout_CXIdxContainerInfo() raises:
    comptime r = reflect[CXIdxContainerInfo]()
    _check_eq("CXIdxContainerInfo.size", Int(size_of[CXIdxContainerInfo]()), 32)
    _check_eq("CXIdxContainerInfo.align", Int(align_of[CXIdxContainerInfo]()), 8)
    _check_eq("CXIdxContainerInfo.cursor.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_CXIdxIBOutletCollectionAttrInfo() raises:
    comptime r = reflect[CXIdxIBOutletCollectionAttrInfo]()
    _check_eq("CXIdxIBOutletCollectionAttrInfo.size", Int(size_of[CXIdxIBOutletCollectionAttrInfo]()), 72)
    _check_eq("CXIdxIBOutletCollectionAttrInfo.align", Int(align_of[CXIdxIBOutletCollectionAttrInfo]()), 8)
    _check_eq("CXIdxIBOutletCollectionAttrInfo.attrInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxIBOutletCollectionAttrInfo.objcClass.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxIBOutletCollectionAttrInfo.classCursor.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("CXIdxIBOutletCollectionAttrInfo.classLoc.offset", Int(r.field_offset[index=3]()), 48)


def test_layout_CXIdxDeclInfo() raises:
    comptime r = reflect[CXIdxDeclInfo]()
    _check_eq("CXIdxDeclInfo.size", Int(size_of[CXIdxDeclInfo]()), 128)
    _check_eq("CXIdxDeclInfo.align", Int(align_of[CXIdxDeclInfo]()), 8)
    _check_eq("CXIdxDeclInfo.entityInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxDeclInfo.cursor.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxDeclInfo.loc.offset", Int(r.field_offset[index=2]()), 40)
    _check_eq("CXIdxDeclInfo.semanticContainer.offset", Int(r.field_offset[index=3]()), 64)
    _check_eq("CXIdxDeclInfo.lexicalContainer.offset", Int(r.field_offset[index=4]()), 72)
    _check_eq("CXIdxDeclInfo.isRedeclaration.offset", Int(r.field_offset[index=5]()), 80)
    _check_eq("CXIdxDeclInfo.isDefinition.offset", Int(r.field_offset[index=6]()), 84)
    _check_eq("CXIdxDeclInfo.isContainer.offset", Int(r.field_offset[index=7]()), 88)
    _check_eq("CXIdxDeclInfo.declAsContainer.offset", Int(r.field_offset[index=8]()), 96)
    _check_eq("CXIdxDeclInfo.isImplicit.offset", Int(r.field_offset[index=9]()), 104)
    _check_eq("CXIdxDeclInfo.attributes.offset", Int(r.field_offset[index=10]()), 112)
    _check_eq("CXIdxDeclInfo.numAttributes.offset", Int(r.field_offset[index=11]()), 120)
    _check_eq("CXIdxDeclInfo.flags.offset", Int(r.field_offset[index=12]()), 124)


def test_layout_CXIdxObjCContainerDeclInfo() raises:
    comptime r = reflect[CXIdxObjCContainerDeclInfo]()
    _check_eq("CXIdxObjCContainerDeclInfo.size", Int(size_of[CXIdxObjCContainerDeclInfo]()), 16)
    _check_eq("CXIdxObjCContainerDeclInfo.align", Int(align_of[CXIdxObjCContainerDeclInfo]()), 8)
    _check_eq("CXIdxObjCContainerDeclInfo.declInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCContainerDeclInfo.kind.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXIdxBaseClassInfo() raises:
    comptime r = reflect[CXIdxBaseClassInfo]()
    _check_eq("CXIdxBaseClassInfo.size", Int(size_of[CXIdxBaseClassInfo]()), 64)
    _check_eq("CXIdxBaseClassInfo.align", Int(align_of[CXIdxBaseClassInfo]()), 8)
    _check_eq("CXIdxBaseClassInfo.base.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxBaseClassInfo.cursor.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxBaseClassInfo.loc.offset", Int(r.field_offset[index=2]()), 40)


def test_layout_CXIdxObjCProtocolRefInfo() raises:
    comptime r = reflect[CXIdxObjCProtocolRefInfo]()
    _check_eq("CXIdxObjCProtocolRefInfo.size", Int(size_of[CXIdxObjCProtocolRefInfo]()), 64)
    _check_eq("CXIdxObjCProtocolRefInfo.align", Int(align_of[CXIdxObjCProtocolRefInfo]()), 8)
    _check_eq("CXIdxObjCProtocolRefInfo.protocol.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCProtocolRefInfo.cursor.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxObjCProtocolRefInfo.loc.offset", Int(r.field_offset[index=2]()), 40)


def test_layout_CXIdxObjCProtocolRefListInfo() raises:
    comptime r = reflect[CXIdxObjCProtocolRefListInfo]()
    _check_eq("CXIdxObjCProtocolRefListInfo.size", Int(size_of[CXIdxObjCProtocolRefListInfo]()), 16)
    _check_eq("CXIdxObjCProtocolRefListInfo.align", Int(align_of[CXIdxObjCProtocolRefListInfo]()), 8)
    _check_eq("CXIdxObjCProtocolRefListInfo.protocols.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCProtocolRefListInfo.numProtocols.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_CXIdxObjCInterfaceDeclInfo() raises:
    comptime r = reflect[CXIdxObjCInterfaceDeclInfo]()
    _check_eq("CXIdxObjCInterfaceDeclInfo.size", Int(size_of[CXIdxObjCInterfaceDeclInfo]()), 24)
    _check_eq("CXIdxObjCInterfaceDeclInfo.align", Int(align_of[CXIdxObjCInterfaceDeclInfo]()), 8)
    _check_eq("CXIdxObjCInterfaceDeclInfo.containerInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCInterfaceDeclInfo.superInfo.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxObjCInterfaceDeclInfo.protocols.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXIdxObjCCategoryDeclInfo() raises:
    comptime r = reflect[CXIdxObjCCategoryDeclInfo]()
    _check_eq("CXIdxObjCCategoryDeclInfo.size", Int(size_of[CXIdxObjCCategoryDeclInfo]()), 80)
    _check_eq("CXIdxObjCCategoryDeclInfo.align", Int(align_of[CXIdxObjCCategoryDeclInfo]()), 8)
    _check_eq("CXIdxObjCCategoryDeclInfo.containerInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCCategoryDeclInfo.objcClass.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxObjCCategoryDeclInfo.classCursor.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("CXIdxObjCCategoryDeclInfo.classLoc.offset", Int(r.field_offset[index=3]()), 48)
    _check_eq("CXIdxObjCCategoryDeclInfo.protocols.offset", Int(r.field_offset[index=4]()), 72)


def test_layout_CXIdxObjCPropertyDeclInfo() raises:
    comptime r = reflect[CXIdxObjCPropertyDeclInfo]()
    _check_eq("CXIdxObjCPropertyDeclInfo.size", Int(size_of[CXIdxObjCPropertyDeclInfo]()), 24)
    _check_eq("CXIdxObjCPropertyDeclInfo.align", Int(align_of[CXIdxObjCPropertyDeclInfo]()), 8)
    _check_eq("CXIdxObjCPropertyDeclInfo.declInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxObjCPropertyDeclInfo.getter.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxObjCPropertyDeclInfo.setter.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXIdxCXXClassDeclInfo() raises:
    comptime r = reflect[CXIdxCXXClassDeclInfo]()
    _check_eq("CXIdxCXXClassDeclInfo.size", Int(size_of[CXIdxCXXClassDeclInfo]()), 24)
    _check_eq("CXIdxCXXClassDeclInfo.align", Int(align_of[CXIdxCXXClassDeclInfo]()), 8)
    _check_eq("CXIdxCXXClassDeclInfo.declInfo.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxCXXClassDeclInfo.bases.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxCXXClassDeclInfo.numBases.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_CXIdxEntityRefInfo() raises:
    comptime r = reflect[CXIdxEntityRefInfo]()
    _check_eq("CXIdxEntityRefInfo.size", Int(size_of[CXIdxEntityRefInfo]()), 96)
    _check_eq("CXIdxEntityRefInfo.align", Int(align_of[CXIdxEntityRefInfo]()), 8)
    _check_eq("CXIdxEntityRefInfo.kind.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXIdxEntityRefInfo.cursor.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("CXIdxEntityRefInfo.loc.offset", Int(r.field_offset[index=2]()), 40)
    _check_eq("CXIdxEntityRefInfo.referencedEntity.offset", Int(r.field_offset[index=3]()), 64)
    _check_eq("CXIdxEntityRefInfo.parentEntity.offset", Int(r.field_offset[index=4]()), 72)
    _check_eq("CXIdxEntityRefInfo.container.offset", Int(r.field_offset[index=5]()), 80)
    _check_eq("CXIdxEntityRefInfo.role.offset", Int(r.field_offset[index=6]()), 88)


def test_layout_IndexerCallbacks() raises:
    comptime r = reflect[IndexerCallbacks]()
    _check_eq("IndexerCallbacks.size", Int(size_of[IndexerCallbacks]()), 64)
    _check_eq("IndexerCallbacks.align", Int(align_of[IndexerCallbacks]()), 8)
    _check_eq("IndexerCallbacks.abortQuery.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("IndexerCallbacks.diagnostic.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("IndexerCallbacks.enteredMainFile.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("IndexerCallbacks.ppIncludedFile.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("IndexerCallbacks.importedASTFile.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("IndexerCallbacks.startedTranslationUnit.offset", Int(r.field_offset[index=5]()), 40)
    _check_eq("IndexerCallbacks.indexDeclaration.offset", Int(r.field_offset[index=6]()), 48)
    _check_eq("IndexerCallbacks.indexEntityReference.offset", Int(r.field_offset[index=7]()), 56)


def test_layout_CXComment() raises:
    comptime r = reflect[CXComment]()
    _check_eq("CXComment.size", Int(size_of[CXComment]()), 16)
    _check_eq("CXComment.align", Int(align_of[CXComment]()), 8)
    _check_eq("CXComment.ASTNode.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("CXComment.TranslationUnit.offset", Int(r.field_offset[index=1]()), 8)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
